service: dio-live-serverless-aws
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:scan
            Resource:
              - arn:aws:dynamodb:us-east-1:167880115321:table/ItemTableName

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  insertItem:
    handler: src/insertItem.handle
    events:
      - httpApi:
          path: /item
          method: post
  fetchItems:
    handler: src/fetchItems.handle
    events:
      - httpApi:
          path: /items
          method: get
  fetchItem:
    handler: src/fetchItem.handle
    events:
      - httpApi:
          path: /items/{id}
          method: get
  updateItem:
    handler: src/updateItem.handle
    events:
      - httpApi:
          path: /items/{id}
          method: put

resources:
  Resources:
    ItemTableNew:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemTableNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
